### ISSUE TITLE
[5] Negative Social Media Post Escalator

### ISSUE THREAD

**Issue by seta-harryvu** [veritone/automate-flow-templates#14]
Overview
Sentiment analysis of social streams, emails, & text messages, and escalation of negative posts to customer service rep to respond.

**Comment by seta-harryvu** [comment]
Document: https://docs.google.com/document/d/1ojYJzJPK__U_tyFshZP3HuS0_5htiSLL0hIDygcXVb0/edit
Hi @aMacDawg 
Please help us to run the mutation to add it to PROD

**Comment by seta-harryvu** [comment]
Ran the creation mutation script successfully on Stage, created the flow from the template successfully.
FYI @kfiry @aMacDawg

**Comment by aMacDawg** [comment]
@seta-harryvu @kfiry , this flow template has been published to production:

```
{
  "data": {
    "createFlowTemplate": {
      "id": "37",
      "title": "Negative Social Media Post Escalator",
      "subtitle": "Run sentiment analysis on social streams, emails, & text messages, and escalate detected negative posts to a customer service rep to quickly respond."
      }
   }
}
```
