### ISSUE TITLE
[4] Twitter Temp Bot

### ISSUE THREAD

**Issue by seta-harryvu** [veritone/automate-flow-templates#18]
Overview
Scrape tweets from either a user (or given users) or a topic/hashtag and run sentiment analysis.

**Comment by robertkieu** [comment]
Need developer account to get twitter feeds from twitter API.
I created a developer account on twitter and waiting for approval before we can continue.

**Comment by robertkieu** [comment]
@seta-harryvu Can you help me create a twitter developer account? I created but seem they didn't approve for me.

**Comment by seta-harryvu** [comment]
Document: https://docs.google.com/document/d/1rCT7h5Tk68H1D1CBYQVoYHspnRVrqf2-ZLRIBx65RNQ/edit
hi @aMacDawg 
please help us to run the mutation on PROD as we have run on Stage

**Comment by seta-harryvu** [comment]
Ran the creation mutation script successfully on Stage, created the flow from the template successfully.
FYI @kfiry @aMacDawg

**Comment by aMacDawg** [comment]
@seta-harryvu @kfiry , this templated has been created in production:

```
{
  "data": {
    "flows": {
      "records": [
        {
          "id": "35",
          "title": "Twitter Temp Bot",
          "categories": [
            "Social Media,aiWARE,Contact Center"
          ],
          "tags": [
            "Social Media",
            "Twitter",
            "Contact Center"
          ]
        }
      ]
    }
  }
}
```
