### ISSUE TITLE
[5] Call Center Content Analytics

### ISSUE THREAD

**Issue by seta-harryvu** [veritone/automate-flow-templates#5]
Overview
Use Topic Extraction engines to tag calls with key topics for realtime escalation & future analytics of common trends.

Details
Need to input a mapping table that which topic will escalate to who. Based on the mapping table and detected topic, the output of the flow will be the name of the higher manager.

**Comment by seta-harryvu** [comment]
Document: https://docs.google.com/document/d/1yn7CRLyM7pF-kxc4T6dDF7BPDItplBSry4J196dUKI8/edit
@aMacDawg 
Please help us to run the mutation on PROD to create the flow template.

**Comment by seta-harryvu** [comment]
Ran the creation mutation script successfully on Stage, created the flow from the template successfully.
FYI @kfiry @aMacDawg

**Comment by aMacDawg** [comment]
@seta-harryvu @kfiry , this template has been published:

```
{
  "data": {
    "createFlowTemplate": {
      "id": "36",
      "title": "Support Call Analytics Reporter",
      "subtitle": "Use summary and Content classification engines to tag calls with key topics for realtime escalation & future analytics of common trends.",
      "categories": [
        "Content Classification,Contact Center"
      ]
     }
  }
}
```
