### ISSUE TITLE
[6] Measuring Latency: Implement a cron service for calculating the final report and upload to google docs

### ISSUE THREAD

**Issue by gianghoang-seta** [veritone/automate-flow-templates#52]
After Measuring Latency Flow completed, a cron service running on local server (need to finger out which is server) will pick up the latest log files, create summary report and add it into a google sheet.
The google sheet URL will be published and send along with a notification email.
The final report will look like: https://docs.google.com/spreadsheets/u/2/d/1MYyNHYBF_za7Jtp7jMQKSwO35GOnH-jY/edit?usp=drive_web&ouid=104800101369090949302&dls=true

**Comment by seta-harryvu** [comment]
Need to implement the summary report in the flow

**Comment by seta-harryvu** [comment]
Close for now
