### ISSUE TITLE
[4] Call Center Automated Creation of Support Tickets

### ISSUE THREAD

**Issue by seta-harryvu** [veritone/automate-flow-templates#6]
Use AI to automatically create support tickets based on conversation details and context.

**Comment by aMacDawg** [comment]
hi @seta-harryvu @viettran-seta do we have a link to this in Automate Studio in the Automate training org?

**Comment by seta-harryvu** [comment]
This documnent link: https://docs.google.com/document/d/10AW8LBQ8EmCxAtewDH58Mo4uCBnLnlvAk7q6qNlGPiQ/edit
This is flow URL: https://automate.veritone.com/flow/8fb8ec59-9e46-4867-9905-7b0fdca2fe6d/8bb89998-9a5e-4bbe-b00e-5b3a13881f8e

@aMacDawg  FYI

**Comment by seta-harryvu** [comment]
hi @aMacDawg 
Please help us to run the mutation on PROD as we have updated the mutation  into the doc and tried to run on Stage.

**Comment by seta-harryvu** [comment]
Ran the creation mutation script successfully on Stage, created the flow from the template successfully.
FYI @kfiry @aMacDawg

**Comment by aMacDawg** [comment]
@seta-harryvu @kfiry , this template has been created:

```
{
  "data": {
    "createFlowTemplate": {
      "id": "34",
      "title": "Support Tickets Automator",
      "subtitle": "Use AI to automatically create support tickets based on conversation details and context."
   }
  }
}
```

**Comment by seta-harryvu** [comment]
[Support ticket automator.txt](https://github.com/veritone/automate-flow-templates/files/5584022/Support.ticket.automator.txt)
Need to update a bit.

**Comment by seta-harryvu** [comment]
Added to PROD
